name: Cache Prime and Verify

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          if [ ! -f package.json ]; then
            cat > package.json <<'JSON'
{
  "name": "cache-demo",
  "version": "1.0.0",
  "dependencies": { "left-pad": "1.3.0" }
}
JSON
          fi
          npm install --no-audit --no-fund

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            node_modules
          key: cache-1798f29

      - name: prime-cache-1798f29
        run: |
          echo "Cache hit status: ${{ steps.cache.outputs.cache-hit }}"
          if [ "${{ steps.cache.outputs.cache-hit }}" = "true" ]; then
            echo "Cache result: HIT"
          else
            echo "Cache result: MISS"
          fi

